# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: node.yml

on:
  push:
    branches:
    - master
    - 'releases/**'
    - '**'
  pull_request:
    branches:
    - master
    - 'releases/**'
    - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: yarn.lock
    - run: sudo apt-get install libtool m4 make g++ autoconf # debian/ubuntu
    - run: |
        make report
    - run: |
        make nvm
    - run: |
        make report
    - run: |
        make install run-build
